name: Add Team to Organization
description: Request adding a team to the GitHub organization as a member
title: "[Add Team To Org] Add <Enter Team Name> to Organization"
labels:
  - add-team-to-org
body:
  - type: markdown
    attributes:
      value: |
        ## Add Team to Organization

        Use this issue to request adding a team to the GitHub organization owned by this GitHub organization. The team will be added as a member. After creating the issue, a member of the IssueOps approver team must add a comment with the `.approve` command. The workflow will add the team to the organization and comment on this issue with the result.

        **Instructions**:
        - Use the fields below to provide the team name and a description of the request.
        - Once complete, enter a comment with the command `.submit`. This will submit the issue to the approval users.
        - Only approved users can trigger the team addition.
        - If approved, the approver will enter a comment with the command `.approve`. This will initiate the addition of the team to the organization as a member.
        - If denied, the approver will enter a comment with the command `.deny`. This will close the issue and comment that the request was denied.
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: The name of the team to be added to the organization
      placeholder: Team Name
    validations:
      required: true
  - type: textarea
    id: team-description
    attributes:
      label: Description
      description: Provide a brief description about this team.
      placeholder: What is this team all about?
    validations:
      required: true
