name: Add Member to Team
description: Request adding a member to an existing team with a specified role
title: "[Add Member To Team] Add <Enter User Name> to <Enter Team Name>"
labels:
  - add-member-to-team
body:
  - type: markdown
    attributes:
      value: |
        ## Add Member to Team

        Use this issue to request adding a member to an existing team owned by this GitHub organization. After creating the issue, a member of the IssueOps approver team must add a comment with the `.approve` command. The workflow will add the member to the team with the specified role and comment on this issue with the result.

        **Instructions**:
        - Use the fields below to provide the member and team details.
        - Once complete, enter a comment with the command `.submit`. This will submit the issue to the approval users.
        - Only approved users can trigger the user addition.
        - If approved, the approver will enter a comment with the command `.approve`. This will initiate the addition of the member to the team.
        - If denied, the approver will enter a comment with the command `.deny`. This will close the issue and comment that the request was denied.
  - type: input
    id: member-name
    attributes:
      label: Member Name
      description: The GitHub username of the member to be added to the team
      placeholder: GitHub Member
    validations:
      required: true
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: The name of the existing team to which the user should be added
      placeholder: Team Name
    validations:
      required: true
  - type: dropdown
    id: team-role
    attributes:
      label: Team Role
      description: The role the user will have in the team
      options:
        - Member
        - Maintainer
    validations:
      required: true
