name: Archive A Repository
description: Request to archive an existing repository
title: "[Archive Repository] <Enter Repository Name>"
labels:
  - archive-repo
body:
  - type: markdown
    attributes:
      value: |
        ## Archive Repository

        Use this issue to request archiving of an existing repository owned by this GitHub organization. After creating the issue, a member of the IssueOps approver team must add a comment with the `.approve` command. The workflow will archive the repository and comment on this issue with the result.

        **Instructions**:
        - Use the fields below to specify the repository details.
        - Once complete, enter a comment with the command `.submit`. This will submit the issue to the approval users.
        - Only approved users can trigger the repository archiving.
        - If approved, the approver will enter a comment with the command `.approve`. This will initiate the archiving of the repository.
        - If denied, the approver will enter a comment with the command `.deny`. This will close the issue and enter a comment that the request was denied.
  - type: input
    id: repo-name
    attributes:
      label: Repository Name
      description: The name of the repository you would like to archive
      placeholder: Repository Name
    validations:
      required: true
  - type: textarea
    id: archive-reason
    attributes:
      label: Reason For Archiving
      description: Provide a brief explanation for why this repository should be archived
      placeholder: e.g., Project is no longer active, or repository is deprecated
    validations:
      required: true
